# Generated by Django 5.2.15 on 2026-07-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0005_alter_checks_id_alter_scanprofiles_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checks',
            name='category',
            field=models.CharField(choices=[('kernel', 'Ядро'), ('ssh', 'SSH'), ('files', 'Файлы'), ('grub', 'GRUB'), ('pam', 'PAM/Пароли'), ('services', 'Сервисы'), ('pentest', 'PenTest')], max_length=10, verbose_name='Категория'),
        ),
    ]
